name: Terraform Workflow

on:
  pull_request:
    types: [opened, edited, reopened, synchronize, closed]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  terraform:
    permissions:
      contents: read
      id-token: write
      pull-requests: write
      security-events: write
      actions: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: google-github-actions/auth@v0.7.0
        with:
          create_credentials_file: 'true'
          workload_identity_provider: "projects/266584906178/locations/global/workloadIdentityPools/github/providers/github"
          service_account: tf-project-creator@terraform-state-322020.iam.gserviceaccount.com


      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Init Terraform
        run: |
          terraform init
      - name: Validate Terraform Configuration
        run: |
          terraform validate

      - name: Terraform Plan
        id: plan
        run: |
          terraform plan -out=tfplan 
        env:
          GOOGLE_CREDENTIALS: ${{secrets.GCP_CI_SERVICE_ACCOUNT}}
      - name: Checkov GitHub Action
        uses: bridgecrewio/checkov-action@v12
        with:
          # This will add both a CLI output to the console and create a results.sarif file
          output_format: cli,sarif
          output_file_path: console,results.sarif
          #skip_check: CKV_A
          download_external_modules: true
          soft_fail: true
        
      # - name: Upload SARIF file
      #   uses: github/codeql-action/upload-sarif@v2

      - name: Store Terraform Plan Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: tfplan

      - name: Apply Terraform Changes
        if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
        run: |
          terraform apply -auto-approve tfplan 
